# Generated by Django 2.2.5 on 2019-09-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("project", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="workdetail",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_details",
                to="project.Project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="cause",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="crew",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="division",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="timecost",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="workorderstatus",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="workrequeststatus",
            name="code",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
