# Generated by Django 2.2.5 on 2019-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("project", "0002_auto_20190928_1602")]

    operations = [
        migrations.AlterField(
            model_name="workdetail",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workdetail",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
