# Generated by Django 2.2.5 on 2019-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("project", "0003_auto_20190928_1610")]

    operations = [
        migrations.AlterField(
            model_name="resource", name="code", field=models.CharField(max_length=64)
        ),
        migrations.AlterUniqueTogether(
            name="resource", unique_together={("code", "type")}
        ),
    ]
